# Generated by Django 2.0.2 on 2018-03-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('station_id', models.IntegerField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('time_retire', models.TextField(blank=True, null=True)),
                ('route_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'arrivals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('station_id', models.IntegerField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('date_retire', models.TextField(blank=True, null=True)),
                ('time_retire', models.TextField(blank=True, null=True)),
                ('route_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'departures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('task_id', models.IntegerField(blank=True, null=True)),
                ('seq_retire', models.IntegerField(blank=True, null=True)),
                ('train_id', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('departure_id', models.IntegerField(blank=True, null=True)),
                ('arrival_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'routes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('sn', models.TextField(blank=True, null=True)),
                ('chn_name', models.TextField(blank=True, null=True)),
                ('eng_name', models.TextField(blank=True, null=True)),
                ('line_id', models.IntegerField(blank=True, null=True)),
                ('distance', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('task', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tasks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('sn', models.TextField(blank=True, null=True)),
                ('train_type_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trains',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrainType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('maker', models.TextField(blank=True, null=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'train_types',
                'managed': False,
            },
        ),
    ]
