# Generated by Django 2.0.2 on 2018-03-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sn', models.TextField(blank=True, null=True, verbose_name='Bike SN')),
            ],
            options={
                'db_table': 'bikes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BikeService',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bike_services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BikeSubtype',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True, verbose_name='Bike type')),
            ],
            options={
                'db_table': 'bike_subtypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BikeType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('codename', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bike_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.TextField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('departure_region', models.TextField(blank=True, null=True)),
                ('departure_place', models.TextField(blank=True, null=True)),
                ('departure_coordinate', models.TextField(blank=True, null=True)),
                ('arrival_region', models.TextField(blank=True, null=True)),
                ('arrival_place', models.TextField(blank=True, null=True)),
                ('arrival_coordinate', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('distance', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trips',
                'managed': False,
            },
        ),
    ]
